// Generated by gencpp from file qt_motors_controller/home.msg
// DO NOT EDIT!


#ifndef QT_MOTORS_CONTROLLER_MESSAGE_HOME_H
#define QT_MOTORS_CONTROLLER_MESSAGE_HOME_H

#include <ros/service_traits.h>


#include <qt_motors_controller/homeRequest.h>
#include <qt_motors_controller/homeResponse.h>


namespace qt_motors_controller
{

struct home
{

typedef homeRequest Request;
typedef homeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct home
} // namespace qt_motors_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_motors_controller::home > {
  static const char* value()
  {
    return "018aa38faa01fecffa7a4eb6cad48ceb";
  }

  static const char* value(const ::qt_motors_controller::home&) { return value(); }
};

template<>
struct DataType< ::qt_motors_controller::home > {
  static const char* value()
  {
    return "qt_motors_controller/home";
  }

  static const char* value(const ::qt_motors_controller::home&) { return value(); }
};


// service_traits::MD5Sum< ::qt_motors_controller::homeRequest> should match 
// service_traits::MD5Sum< ::qt_motors_controller::home > 
template<>
struct MD5Sum< ::qt_motors_controller::homeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_motors_controller::home >::value();
  }
  static const char* value(const ::qt_motors_controller::homeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_motors_controller::homeRequest> should match 
// service_traits::DataType< ::qt_motors_controller::home > 
template<>
struct DataType< ::qt_motors_controller::homeRequest>
{
  static const char* value()
  {
    return DataType< ::qt_motors_controller::home >::value();
  }
  static const char* value(const ::qt_motors_controller::homeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_motors_controller::homeResponse> should match 
// service_traits::MD5Sum< ::qt_motors_controller::home > 
template<>
struct MD5Sum< ::qt_motors_controller::homeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_motors_controller::home >::value();
  }
  static const char* value(const ::qt_motors_controller::homeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_motors_controller::homeResponse> should match 
// service_traits::DataType< ::qt_motors_controller::home > 
template<>
struct DataType< ::qt_motors_controller::homeResponse>
{
  static const char* value()
  {
    return DataType< ::qt_motors_controller::home >::value();
  }
  static const char* value(const ::qt_motors_controller::homeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_MOTORS_CONTROLLER_MESSAGE_HOME_H
