// Generated by gencpp from file qt_motors_controller/set_control_mode.msg
// DO NOT EDIT!


#ifndef QT_MOTORS_CONTROLLER_MESSAGE_SET_CONTROL_MODE_H
#define QT_MOTORS_CONTROLLER_MESSAGE_SET_CONTROL_MODE_H

#include <ros/service_traits.h>


#include <qt_motors_controller/set_control_modeRequest.h>
#include <qt_motors_controller/set_control_modeResponse.h>


namespace qt_motors_controller
{

struct set_control_mode
{

typedef set_control_modeRequest Request;
typedef set_control_modeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_control_mode
} // namespace qt_motors_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_motors_controller::set_control_mode > {
  static const char* value()
  {
    return "29ec7411588be56f1e5fa3f64ddace43";
  }

  static const char* value(const ::qt_motors_controller::set_control_mode&) { return value(); }
};

template<>
struct DataType< ::qt_motors_controller::set_control_mode > {
  static const char* value()
  {
    return "qt_motors_controller/set_control_mode";
  }

  static const char* value(const ::qt_motors_controller::set_control_mode&) { return value(); }
};


// service_traits::MD5Sum< ::qt_motors_controller::set_control_modeRequest> should match 
// service_traits::MD5Sum< ::qt_motors_controller::set_control_mode > 
template<>
struct MD5Sum< ::qt_motors_controller::set_control_modeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_motors_controller::set_control_mode >::value();
  }
  static const char* value(const ::qt_motors_controller::set_control_modeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_motors_controller::set_control_modeRequest> should match 
// service_traits::DataType< ::qt_motors_controller::set_control_mode > 
template<>
struct DataType< ::qt_motors_controller::set_control_modeRequest>
{
  static const char* value()
  {
    return DataType< ::qt_motors_controller::set_control_mode >::value();
  }
  static const char* value(const ::qt_motors_controller::set_control_modeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_motors_controller::set_control_modeResponse> should match 
// service_traits::MD5Sum< ::qt_motors_controller::set_control_mode > 
template<>
struct MD5Sum< ::qt_motors_controller::set_control_modeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_motors_controller::set_control_mode >::value();
  }
  static const char* value(const ::qt_motors_controller::set_control_modeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_motors_controller::set_control_modeResponse> should match 
// service_traits::DataType< ::qt_motors_controller::set_control_mode > 
template<>
struct DataType< ::qt_motors_controller::set_control_modeResponse>
{
  static const char* value()
  {
    return DataType< ::qt_motors_controller::set_control_mode >::value();
  }
  static const char* value(const ::qt_motors_controller::set_control_modeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_MOTORS_CONTROLLER_MESSAGE_SET_CONTROL_MODE_H
