qt_ros_vosk_app:
  audio_rate: 16000
  audio_topic: '/qt_respeaker_app/channel0'

  vosk:
    vosk_model_path: '/home/qtrobot/robot/vosk/models/'  
    default_language: 'en_US'
  
  hotword:
    hotword_model: '/home/qtrobot/catkin_ws/src/qt_ros_vosk_app/data/qt_robot.ppn'
    hotword: 'QTrobot'
    access_key: 'K8eJOJwOEKK0AxUzCVy8Rd2lV6uVgxcvsFkEMt561J+kwP8Ng1V9eg=='
    sensitivity: 0.7
    publish_hotword: true
    feedback_audio: '/home/qtrobot/catkin_ws/src/qt_ros_vosk_app/data/bell.wav'
