#std_msgs/Header header
int32 id
#The normalized projective (x, y) coordinate of the right hand
float32[] right_projection
#The (x,y,z) coordinate of the right hand in the world system.
float32[] right_real
bool right_click
int32 right_pressure
#The normalized projective (x, y) coordinate of the left hand
float32[] left_projection
#The (x,y,z) coordinate of the left hand in the world system.
float32[] left_real
bool left_click
int32 left_pressure
