(cl:defpackage qt_motors_controller-srv
  (:use )
  (:export
   "HOME"
   "<HOME-REQUEST>"
   "HOME-REQUEST"
   "<HOME-RESPONSE>"
   "HOME-RESPONSE"
   "SET_CONTROL_MODE"
   "<SET_CONTROL_MODE-REQUEST>"
   "SET_CONTROL_MODE-REQUEST"
   "<SET_CONTROL_MODE-RESPONSE>"
   "SET_CONTROL_MODE-RESPONSE"
   "SET_VELOCITY"
   "<SET_VELOCITY-REQUEST>"
   "SET_VELOCITY-REQUEST"
   "<SET_VELOCITY-RESPONSE>"
   "SET_VELOCITY-RESPONSE"
  ))

