qt_respeaker_app:
  update_rate: 10.0
  suppress_pyaudio_error : true 
  tuning:
    AGCONOFF: 0
    AGCGAIN: 15.0    
    STATNOISEONOFF_SR: 1
    MIN_NS_SR: 0.01
    GAMMA_NS_SR: 1.80
    CNIONOFF: 0
    
