qt_respeaker_app:
  update_rate: 10.0
  suppress_pyaudio_error : true 
  # mic_device_id: 2
  tuning:
    AGCONOFF: 1
    AGCGAIN: 30.0
    STATNOISEONOFF_SR: 1
    MIN_NS_SR: 0.01
    GAMMA_NS_SR: 1.80
    CNIONOFF: 0
    
