// Generated by gencpp from file qt_gesture_controller/gesture_record.msg
// DO NOT EDIT!


#ifndef QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_RECORD_H
#define QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_RECORD_H

#include <ros/service_traits.h>


#include <qt_gesture_controller/gesture_recordRequest.h>
#include <qt_gesture_controller/gesture_recordResponse.h>


namespace qt_gesture_controller
{

struct gesture_record
{

typedef gesture_recordRequest Request;
typedef gesture_recordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gesture_record
} // namespace qt_gesture_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_gesture_controller::gesture_record > {
  static const char* value()
  {
    return "f920c6a17216e8fe1e02e50dada8c9d0";
  }

  static const char* value(const ::qt_gesture_controller::gesture_record&) { return value(); }
};

template<>
struct DataType< ::qt_gesture_controller::gesture_record > {
  static const char* value()
  {
    return "qt_gesture_controller/gesture_record";
  }

  static const char* value(const ::qt_gesture_controller::gesture_record&) { return value(); }
};


// service_traits::MD5Sum< ::qt_gesture_controller::gesture_recordRequest> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_record > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_recordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_record >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_recordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_recordRequest> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_record > 
template<>
struct DataType< ::qt_gesture_controller::gesture_recordRequest>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_record >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_recordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_gesture_controller::gesture_recordResponse> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_record > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_recordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_record >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_recordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_recordResponse> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_record > 
template<>
struct DataType< ::qt_gesture_controller::gesture_recordResponse>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_record >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_recordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_RECORD_H
