// Generated by gencpp from file qt_gesture_controller/gesture_stop.msg
// DO NOT EDIT!


#ifndef QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_STOP_H
#define QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_STOP_H

#include <ros/service_traits.h>


#include <qt_gesture_controller/gesture_stopRequest.h>
#include <qt_gesture_controller/gesture_stopResponse.h>


namespace qt_gesture_controller
{

struct gesture_stop
{

typedef gesture_stopRequest Request;
typedef gesture_stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gesture_stop
} // namespace qt_gesture_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_gesture_controller::gesture_stop > {
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::qt_gesture_controller::gesture_stop&) { return value(); }
};

template<>
struct DataType< ::qt_gesture_controller::gesture_stop > {
  static const char* value()
  {
    return "qt_gesture_controller/gesture_stop";
  }

  static const char* value(const ::qt_gesture_controller::gesture_stop&) { return value(); }
};


// service_traits::MD5Sum< ::qt_gesture_controller::gesture_stopRequest> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_stop > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_stop >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_stopRequest> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_stop > 
template<>
struct DataType< ::qt_gesture_controller::gesture_stopRequest>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_stop >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_gesture_controller::gesture_stopResponse> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_stop > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_stop >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_stopResponse> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_stop > 
template<>
struct DataType< ::qt_gesture_controller::gesture_stopResponse>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_stop >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_STOP_H
