// Generated by gencpp from file qt_gesture_controller/gesture_save.msg
// DO NOT EDIT!


#ifndef QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_SAVE_H
#define QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_SAVE_H

#include <ros/service_traits.h>


#include <qt_gesture_controller/gesture_saveRequest.h>
#include <qt_gesture_controller/gesture_saveResponse.h>


namespace qt_gesture_controller
{

struct gesture_save
{

typedef gesture_saveRequest Request;
typedef gesture_saveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gesture_save
} // namespace qt_gesture_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_gesture_controller::gesture_save > {
  static const char* value()
  {
    return "088f4facf8938c7925f9bdd7cacce95b";
  }

  static const char* value(const ::qt_gesture_controller::gesture_save&) { return value(); }
};

template<>
struct DataType< ::qt_gesture_controller::gesture_save > {
  static const char* value()
  {
    return "qt_gesture_controller/gesture_save";
  }

  static const char* value(const ::qt_gesture_controller::gesture_save&) { return value(); }
};


// service_traits::MD5Sum< ::qt_gesture_controller::gesture_saveRequest> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_save > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_saveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_save >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_saveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_saveRequest> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_save > 
template<>
struct DataType< ::qt_gesture_controller::gesture_saveRequest>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_save >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_saveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_gesture_controller::gesture_saveResponse> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_save > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_saveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_save >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_saveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_saveResponse> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_save > 
template<>
struct DataType< ::qt_gesture_controller::gesture_saveResponse>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_save >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_saveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_SAVE_H
