// Generated by gencpp from file qt_gesture_controller/gesture_list.msg
// DO NOT EDIT!


#ifndef QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_LIST_H
#define QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_LIST_H

#include <ros/service_traits.h>


#include <qt_gesture_controller/gesture_listRequest.h>
#include <qt_gesture_controller/gesture_listResponse.h>


namespace qt_gesture_controller
{

struct gesture_list
{

typedef gesture_listRequest Request;
typedef gesture_listResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct gesture_list
} // namespace qt_gesture_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_gesture_controller::gesture_list > {
  static const char* value()
  {
    return "fff31f89d10c3103fdbdb3a5212feb94";
  }

  static const char* value(const ::qt_gesture_controller::gesture_list&) { return value(); }
};

template<>
struct DataType< ::qt_gesture_controller::gesture_list > {
  static const char* value()
  {
    return "qt_gesture_controller/gesture_list";
  }

  static const char* value(const ::qt_gesture_controller::gesture_list&) { return value(); }
};


// service_traits::MD5Sum< ::qt_gesture_controller::gesture_listRequest> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_list > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_listRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_list >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_listRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_listRequest> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_list > 
template<>
struct DataType< ::qt_gesture_controller::gesture_listRequest>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_list >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_listRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_gesture_controller::gesture_listResponse> should match 
// service_traits::MD5Sum< ::qt_gesture_controller::gesture_list > 
template<>
struct MD5Sum< ::qt_gesture_controller::gesture_listResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_gesture_controller::gesture_list >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_listResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_gesture_controller::gesture_listResponse> should match 
// service_traits::DataType< ::qt_gesture_controller::gesture_list > 
template<>
struct DataType< ::qt_gesture_controller::gesture_listResponse>
{
  static const char* value()
  {
    return DataType< ::qt_gesture_controller::gesture_list >::value();
  }
  static const char* value(const ::qt_gesture_controller::gesture_listResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_GESTURE_CONTROLLER_MESSAGE_GESTURE_LIST_H
