// Generated by gencpp from file qt_robot_interface/audio_play.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_AUDIO_PLAY_H
#define QT_ROBOT_INTERFACE_MESSAGE_AUDIO_PLAY_H

#include <ros/service_traits.h>


#include <qt_robot_interface/audio_playRequest.h>
#include <qt_robot_interface/audio_playResponse.h>


namespace qt_robot_interface
{

struct audio_play
{

typedef audio_playRequest Request;
typedef audio_playResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct audio_play
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::audio_play > {
  static const char* value()
  {
    return "52268a262dc8cf03d5103995c9714ffa";
  }

  static const char* value(const ::qt_robot_interface::audio_play&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::audio_play > {
  static const char* value()
  {
    return "qt_robot_interface/audio_play";
  }

  static const char* value(const ::qt_robot_interface::audio_play&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::audio_playRequest> should match 
// service_traits::MD5Sum< ::qt_robot_interface::audio_play > 
template<>
struct MD5Sum< ::qt_robot_interface::audio_playRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::audio_play >::value();
  }
  static const char* value(const ::qt_robot_interface::audio_playRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::audio_playRequest> should match 
// service_traits::DataType< ::qt_robot_interface::audio_play > 
template<>
struct DataType< ::qt_robot_interface::audio_playRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::audio_play >::value();
  }
  static const char* value(const ::qt_robot_interface::audio_playRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::audio_playResponse> should match 
// service_traits::MD5Sum< ::qt_robot_interface::audio_play > 
template<>
struct MD5Sum< ::qt_robot_interface::audio_playResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::audio_play >::value();
  }
  static const char* value(const ::qt_robot_interface::audio_playResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::audio_playResponse> should match 
// service_traits::DataType< ::qt_robot_interface::audio_play > 
template<>
struct DataType< ::qt_robot_interface::audio_playResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::audio_play >::value();
  }
  static const char* value(const ::qt_robot_interface::audio_playResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_AUDIO_PLAY_H
