// Generated by gencpp from file qt_robot_interface/behavior_talk_text.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_BEHAVIOR_TALK_TEXT_H
#define QT_ROBOT_INTERFACE_MESSAGE_BEHAVIOR_TALK_TEXT_H

#include <ros/service_traits.h>


#include <qt_robot_interface/behavior_talk_textRequest.h>
#include <qt_robot_interface/behavior_talk_textResponse.h>


namespace qt_robot_interface
{

struct behavior_talk_text
{

typedef behavior_talk_textRequest Request;
typedef behavior_talk_textResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct behavior_talk_text
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::behavior_talk_text > {
  static const char* value()
  {
    return "27e2edee8a095bc44ea85df9f9df3f10";
  }

  static const char* value(const ::qt_robot_interface::behavior_talk_text&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::behavior_talk_text > {
  static const char* value()
  {
    return "qt_robot_interface/behavior_talk_text";
  }

  static const char* value(const ::qt_robot_interface::behavior_talk_text&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_textRequest> should match 
// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_text > 
template<>
struct MD5Sum< ::qt_robot_interface::behavior_talk_textRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::behavior_talk_text >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_textRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::behavior_talk_textRequest> should match 
// service_traits::DataType< ::qt_robot_interface::behavior_talk_text > 
template<>
struct DataType< ::qt_robot_interface::behavior_talk_textRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::behavior_talk_text >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_textRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_textResponse> should match 
// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_text > 
template<>
struct MD5Sum< ::qt_robot_interface::behavior_talk_textResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::behavior_talk_text >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_textResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::behavior_talk_textResponse> should match 
// service_traits::DataType< ::qt_robot_interface::behavior_talk_text > 
template<>
struct DataType< ::qt_robot_interface::behavior_talk_textResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::behavior_talk_text >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_textResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_BEHAVIOR_TALK_TEXT_H
