// Generated by gencpp from file qt_robot_interface/behavior_talk_audio.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_BEHAVIOR_TALK_AUDIO_H
#define QT_ROBOT_INTERFACE_MESSAGE_BEHAVIOR_TALK_AUDIO_H

#include <ros/service_traits.h>


#include <qt_robot_interface/behavior_talk_audioRequest.h>
#include <qt_robot_interface/behavior_talk_audioResponse.h>


namespace qt_robot_interface
{

struct behavior_talk_audio
{

typedef behavior_talk_audioRequest Request;
typedef behavior_talk_audioResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct behavior_talk_audio
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::behavior_talk_audio > {
  static const char* value()
  {
    return "52268a262dc8cf03d5103995c9714ffa";
  }

  static const char* value(const ::qt_robot_interface::behavior_talk_audio&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::behavior_talk_audio > {
  static const char* value()
  {
    return "qt_robot_interface/behavior_talk_audio";
  }

  static const char* value(const ::qt_robot_interface::behavior_talk_audio&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_audioRequest> should match 
// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_audio > 
template<>
struct MD5Sum< ::qt_robot_interface::behavior_talk_audioRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::behavior_talk_audio >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_audioRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::behavior_talk_audioRequest> should match 
// service_traits::DataType< ::qt_robot_interface::behavior_talk_audio > 
template<>
struct DataType< ::qt_robot_interface::behavior_talk_audioRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::behavior_talk_audio >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_audioRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_audioResponse> should match 
// service_traits::MD5Sum< ::qt_robot_interface::behavior_talk_audio > 
template<>
struct MD5Sum< ::qt_robot_interface::behavior_talk_audioResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::behavior_talk_audio >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_audioResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::behavior_talk_audioResponse> should match 
// service_traits::DataType< ::qt_robot_interface::behavior_talk_audio > 
template<>
struct DataType< ::qt_robot_interface::behavior_talk_audioResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::behavior_talk_audio >::value();
  }
  static const char* value(const ::qt_robot_interface::behavior_talk_audioResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_BEHAVIOR_TALK_AUDIO_H
