// Generated by gencpp from file qt_robot_interface/speech_config.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SPEECH_CONFIG_H
#define QT_ROBOT_INTERFACE_MESSAGE_SPEECH_CONFIG_H

#include <ros/service_traits.h>


#include <qt_robot_interface/speech_configRequest.h>
#include <qt_robot_interface/speech_configResponse.h>


namespace qt_robot_interface
{

struct speech_config
{

typedef speech_configRequest Request;
typedef speech_configResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speech_config
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::speech_config > {
  static const char* value()
  {
    return "bb0832ad049396f7ac17944e2242235c";
  }

  static const char* value(const ::qt_robot_interface::speech_config&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::speech_config > {
  static const char* value()
  {
    return "qt_robot_interface/speech_config";
  }

  static const char* value(const ::qt_robot_interface::speech_config&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::speech_configRequest> should match 
// service_traits::MD5Sum< ::qt_robot_interface::speech_config > 
template<>
struct MD5Sum< ::qt_robot_interface::speech_configRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::speech_config >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_configRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::speech_configRequest> should match 
// service_traits::DataType< ::qt_robot_interface::speech_config > 
template<>
struct DataType< ::qt_robot_interface::speech_configRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::speech_config >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_configRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::speech_configResponse> should match 
// service_traits::MD5Sum< ::qt_robot_interface::speech_config > 
template<>
struct MD5Sum< ::qt_robot_interface::speech_configResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::speech_config >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_configResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::speech_configResponse> should match 
// service_traits::DataType< ::qt_robot_interface::speech_config > 
template<>
struct DataType< ::qt_robot_interface::speech_configResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::speech_config >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_configResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SPEECH_CONFIG_H
