// Generated by gencpp from file qt_robot_interface/speech_stop.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SPEECH_STOP_H
#define QT_ROBOT_INTERFACE_MESSAGE_SPEECH_STOP_H

#include <ros/service_traits.h>


#include <qt_robot_interface/speech_stopRequest.h>
#include <qt_robot_interface/speech_stopResponse.h>


namespace qt_robot_interface
{

struct speech_stop
{

typedef speech_stopRequest Request;
typedef speech_stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speech_stop
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::speech_stop > {
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::qt_robot_interface::speech_stop&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::speech_stop > {
  static const char* value()
  {
    return "qt_robot_interface/speech_stop";
  }

  static const char* value(const ::qt_robot_interface::speech_stop&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::speech_stopRequest> should match 
// service_traits::MD5Sum< ::qt_robot_interface::speech_stop > 
template<>
struct MD5Sum< ::qt_robot_interface::speech_stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::speech_stop >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::speech_stopRequest> should match 
// service_traits::DataType< ::qt_robot_interface::speech_stop > 
template<>
struct DataType< ::qt_robot_interface::speech_stopRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::speech_stop >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::speech_stopResponse> should match 
// service_traits::MD5Sum< ::qt_robot_interface::speech_stop > 
template<>
struct MD5Sum< ::qt_robot_interface::speech_stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::speech_stop >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::speech_stopResponse> should match 
// service_traits::DataType< ::qt_robot_interface::speech_stop > 
template<>
struct DataType< ::qt_robot_interface::speech_stopResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::speech_stop >::value();
  }
  static const char* value(const ::qt_robot_interface::speech_stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SPEECH_STOP_H
